# Cluster Name
cluster: hcp0
clusterNamespace: hcp0-cluster

# HyperShift Supported Platform : Valid Values are KubeVirt aka OpenShift Virtualisation, Agent (ISO Based Installer)
hyperShiftPlatform: kubevirt

# Manage Cluster from Hub Cluster Repository
managedCluster: 
  status: "disabled" # Valid values "enabled" or "disabled"
  managedRepo: https://github.com/one-touch-provisioning/otp-gitops.git # Repository that will be used to manage the Cluster resources
  managedRepoBranch: master # Branch to use
  environment:  # Typically this would be dev, test, cicd, prod
  projectName:  # This could be a project, line of business, anything that makes sense to you. This references the folder name
                # within the "environment" folder

# OpenShift Version to deploy
imageName: 4.16.39

# Add Cluster to Existing ClusterSet, else it will automatically join the "global"  and "default" ClusterSets
clusterSet:
  name: "multicloud-cluster-set"
  enabled: false

# Compute Resources to be used for Masters and Workers
nodepool:
  name: hcp0-np-1
  count: 2
  computeCores: 4
  computeMemory: 16Gi
  diskSize: 32Gi

# Network CIDR's to be used
network:
  clusterCidr: 10.132.0.0/14
  serviceCidr: 172.31.0.0/16

# Availability Policy
availabilityPolicy:
  controller: SingleReplica
  infrastructure: SingleReplica

# Everything Secrets
secrets:
    openshiftPullSecretRef: adc32372-cafe-0488-a9ab-6a971a6ca2d8
    openshiftSSHPublicKeyRef: 91b5a6de-a9be-2b91-a3e8-2b09e3390bcb