apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-vsphere-creds
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{.Values.cluster }}
spec:
  encryptedData:
    username: {{ .Values.provider.username }} 
    password: {{ .Values.provider.password }}  
  template:
    data: null
    metadata:
      name: {{ .Values.cluster }}-vsphere-creds
      namespace: '{{ .Values.cluster }}'
    type: Opaque
