apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-install-config
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{.Values.cluster }}
spec:
  encryptedData:
    install-config.yaml: {{ .Values.provider.installConfig }}
  template:
    data: null
    metadata:
      name: {{ .Values.cluster }}-install-config
      namespace: {{ .Values.cluster }} 
    type: Opaque
