apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws
spec:
  data:
  - secretKey: awsAccessKey
    remoteRef:
      key: 0d1d17a7-9d6b-a2b4-6b20-04d87f770fce 
  - secretKey: awsSecretKey
    remoteRef:
      key: 57afa209-35b7-da90-5b92-9621cc27030c
  - secretKey: awsBaseDomain
    remoteRef:
      key: 48dcb7e2-fefe-fb2a-548d-8692d1680408 
  - secretKey: openshiftPullSecret
    remoteRef:
      key: adc32372-cafe-0488-a9ab-6a971a6ca2d8
  - secretKey: openshiftSSHPrivateKey
    remoteRef:
      key: 91b5a6de-a9be-2b91-a3e8-2b09e3390bcb
  - secretKey: openshiftSSHPublicKey
    remoteRef:
      key: 2a4c460c-4443-3d29-ee43-18b21b9c6b3b
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: aws
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cluster.open-cluster-management.io/credentials: ""
          cluster.open-cluster-management.io/type: aws
      type: Opaque
      data:
        aws_access_key_id: "{{ .awsAccessKey | toString }}"
        aws_secret_access_key: "{{ .awsSecretKey | toString }}"
        baseDomain: "{{ .awsBaseDomain | toString }}"
        pullSecret: "{{ .openshiftPullSecret | toString }}"
        ssh-publickey: "{{ .openshiftSSHPublicKey | toString }}"
        ssh-privatekey: "{{ .openshiftSSHPrivateKey | toString }}"