apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterpoolName }}-azure-creds
  annotations:
    argocd.argoproj.io/sync-wave: "410"
    helm.sh/hook-weight: "410"
  namespace: rhacm-clusterpools
spec:
  data:
    - secretKey: azureOsServicePrincipal
      remoteRef:
        key: 4f5caf7a-174c-5890-84b2-d7cffc7a4be7
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.clusterpoolName }}-azure-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        osServicePrincipal.json: |-
          {{ "{{ .azureOsServicePrincipal | toString }}" }}