apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterpoolName }}-azure-creds
  annotations:
    argocd.argoproj.io/sync-wave: "310"
    helm.sh/hook-weight: "310"
  namespace: {{ .Values.clusterpoolName }}
spec:
  data:
    - secretKey: azureOsServicePrincipal
      remoteRef:
        key: ef8a9c51-6300-ff8a-2aa4-aef4c9d8b166
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.clusterpoolName }}-azure-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        osServicePrincipal.json: |-
          {{ "{{ .azureOsServicePrincipal | toString }}" }}