apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterpoolName }}-install-config
  annotations:
    argocd.argoproj.io/sync-wave: "310"
    helm.sh/hook-weight: "310"
  namespace: rhacm-clusterpools 
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: {{ include "cluster.install-config" . | b64enc }} 
type: Opaque
