apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
  name: '{{ .Values.clusterClaimName }}'
  annotations:
    argocd.argoproj.io/sync-wave: "450"
    helm.sh/hook-weight: "450"
    cluster.open-cluster-management.io/createmanagedcluster: "true"
  labels:
    clusterClaimName: {{ .Values.clusterClaimName }} 
  namespace: 'rhacm-clusterpools'
spec:
  clusterPoolName: {{ .Values.clusterPoolName }}

