apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: deploy-storage-nodes-{{ .Values.clusterClaimName }}
  namespace: rhacm-clusterpools
  annotations:
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ .Values.clusterClaimName }}-storage-worker
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: hive.openshift.io/v1
                kind: MachinePool
                metadata:
                  name: {{ .Values.clusterClaimName }}-storage-worker
                  labels:
                    machine.openshift.io/cluster-api-machine-role: infra
                    machine.openshift.io/cluster-api-machine-type: infra
                    node-role.kubernetes.io/infra: ""
                    cluster.ocs.openshift.io/openshift-storage: ""
                  namespace: 'rhacm-clusterpools'
                spec:
                  clusterDeploymentRef:
                    name: {{ "{{hub (lookup \"hive.openshift.io/v1\" \"ClusterClaim\" \"rhacm-clusterpools\" \"{{ .Values.clusterClaimName }}\" ).spec.namespace hub}}" }}
                  name: '{{ fromClusterClaim \"aws-cluster\" }}'
                  platform:
                    platform:
                      azure:
                        osDisk:
                          diskSizeGB: {{ .Values.storage.diskSize }} 
                        type: {{ .Values.storage.machineType }}
                        zones:
                        - "1"
                        - "2"
                        - "3"
                  replicas: 3
                  taints:
                    - key: node-role.kubernetes.io/infra
                      value: reserved
                      effect: NoExecute
                    - key: node-role.kubernetes.io/infra
                      value: reserved
                      effect: NoSchedule