{{- if eq .Values.managedCluster.status "enabled" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.clusterClaimName }}-external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "460"
    helm.sh/hook-weight: "460"
  namespace: openshift-gitops
spec:
  template:
    spec:
      serviceAccountName: openshift-gitops-otp-argocd-application-controller
      containers:
      - name: external-secrets-{{ .Values.clusterClaimName }}
        image: quay.io/openshift/origin-cli:v3.11
        command: ["/bin/bash"]
        args:
        - -c
        - |-
          echo "External secrets"
          CLUSTER_DEPLOYMENT=$(oc get clusterclaim.hive.openshift.io -n rhacm-clusterpools {{ .Values.clusterClaimName }} -o=jsonpath='{.spec.namespace}')
          echo $CLUSTER_DEPLOYMENT
          {{- range .Values.managedCluster.privateRepositoriesAccess }}
          cat <<EOF > {{ .name }}-external-secret.yaml
          apiVersion: external-secrets.io/v1beta1
          kind: ExternalSecret
          metadata:
            name: {{ .name }}-repo-server-token
            namespace: $CLUSTER_DEPLOYMENT
            labels:
              app.kubernetes.io/instance: {{ $.Release.Name }}
            annotations:
              app.kubernetes.io/instance: {{ $.Release.Name }}
              argocd.argoproj.io/compare-options: IgnoreExtraneous
          spec:
            data:
            - secretKey: ghToken
              remoteRef:
                key: {{ .ghTokenSecretId | quote }}
            refreshInterval: 24h0m0s
            secretStoreRef:
              name: {{ .secretStore }}
              kind: ClusterSecretStore
            target:
              creationPolicy: Owner
              template:
                metadata:
                  labels:
                    argocd.argoproj.io/secret-type: repository
                type: Opaque
                data:
                  url: {{ .url }}
                  username: not-used
                  password: |-
                    {{ "{{ .ghToken | toString }}" }}
          EOF
          cat {{ .name }}-external-secret.yaml
          oc apply -f {{ .name }}-external-secret.yaml
          {{- end }}
          echo "End of script."
      restartPolicy: OnFailure
  backoffLimit: 2
{{- end -}}
