apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hypershift-operator-oidc-provider-s3-credentials
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: hypershift-operator-oidc-provider-s3-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: 5b54ad79-136c-4165-7b50-861f67d745c7
