apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: rhacm-providers-cluster-scoped-secrets
spec:
  externalSecretName: {{ .Values.rhacmProviderName }}
  namespaceSelector:
    matchLabels:
      eso-cluster-secrets: enabled
  refreshTime: "1h"
  
  externalSecretSpec:
    refreshInterval: "24h"
    secretStoreRef:
      name: cluster
      kind: ClusterSecretStore
    data:
    {{- if eq .Values.cloudProvider.name "aws" }}
    - secretKey: awsAccessKey 
      remoteRef:
        key: '{{ .Values.awsSecrets.awsAccessKeyRef }}'
    - secretKey: awsSecretKey 
      remoteRef:
        key: '{{ .Values.awsSecrets.awsSecretKeyRef }}'
    - secretKey: awsBaseDomain
      remoteRef:
        key: '{{ .Values.awsSecrets.awsBaseDomainRef }}'
    - secretKey: openshiftPullSecret
      remoteRef:
        key: '{{ .Values.awsSecrets.openshiftPullSecretRef }}'
    - secretKey: openshiftSSHPrivateKey
      remoteRef:
        key: '{{ .Values.awsSecrets.openshiftSSHPrivateKeyRef }}'
    - secretKey: openshiftSSHPublicKey
      remoteRef:
        key: '{{ .Values.awsSecrets.openshiftSSHPublicKeyRef }}'
    {{- end }}
    {{- if eq .Values.cloudProvider.name "azure" }} 
    - secretKey: azureBaseDomain
      remoteRef:
        key: '{{ .Values.azureSecrets.azureBaseDomainRef }}'
    - secretKey: azureBaseDomainResourceGroupName
      remoteRef:
        key: '{{ .Values.azureSecrets.azureBaseDomainResourceGroupNameRef }}'
    - secretKey: azureOsServicePrincipal
      remoteRef:
        key: '{{ .Values.azureSecrets.azureOsServicePrincipalRef }}'
    - secretKey: openshiftPullSecret 
      remoteRef:
        key: '{{ .Values.azureSecrets.openshiftPullSecretRef }}'
    - secretKey: openshiftSSHPrivateKey 
      remoteRef:
        key: '{{ .Values.azureSecrets.openshiftSSHPrivateKeyRef }}'
    - secretKey: openshiftSSHPublicKey 
      remoteRef:
        key: '{{ .Values.azureSecrets.openshiftSSHPublicKeyRef }}'
    {{- end }}
    {{- if eq .Values.cloudProvider.name "gcp" }} 
    - secretKey: gcpBaseDomain
      remoteRef:
        key: '{{ .Values.gcpSecrets.gcpBaseDomainRef }}'
    - secretKey: gcpProjectID
      remoteRef:
        key: '{{ .Values.gcpSecrets.gcpProjectIDRef }}'
    - secretKey: gcpOsServiceAccount
      remoteRef:
        key: '{{ .Values.gcpSecrets.gcpOsServiceAccountRef }}'
    - secretKey: openshiftPullSecret 
      remoteRef:
        key: '{{ .Values.gcpSecrets.openshiftPullSecretRef }}'
    - secretKey: openshiftSSHPrivateKey 
      remoteRef:
        key: '{{ .Values.gcpSecrets.openshiftSSHPrivateKeyRef }}'
    - secretKey: openshiftSSHPublicKey 
      remoteRef:
        key: '{{ .Values.gcpSecrets.openshiftSSHPublicKeyRef }}'
    {{- end }}
    {{- if eq .Values.cloudProvider.name "rhocm" }} 
    - secretKey: ocmAPIToken
      remoteRef:
        key: '{{ .Values.rhocmSecrets.ocmAPITokenRef }}'
    {{-end }}
    target:
      name: {{ .Values.rhacmProviderName }}
      creationPolicy: Owner
      template:
        metadata:
          labels:
            cluster.open-cluster-management.io/credentials: ""
            cluster.open-cluster-management.io/type: {{ .Values.cloudProvider.name }}
        type: Opaque
        data:
          {{- if eq .Values.cloudProvider.name "aws" }}
          aws_access_key_id: |-
            {{ "{{ .awsAccessKey | toString }}" }}
          aws_secret_access_key: |-
            {{ "{{ .awsSecretKey | toString }}" }}
          baseDomain: |-
            {{ "{{ .awsBaseDomain | toString }}" }}
          pullSecret: |- 
            {{ "{{ .openshiftPullSecret | toString }}" }}
          ssh-publickey: |-
            {{ "{{ .openshiftSSHPrivateKey | toString }}" }}
          ssh-privatekey: |- 
            {{ "{{ .openshiftSSHPublicKey | toString }}" }}
          {{- end }}
          {{- if eq .Values.cloudProvider.name "azure" }}
          baseDomain: |-
            "{{ .azureBaseDomain | toString }}"
          baseDomainResourceGroupName: |- 
            "{{ .azureBaseDomainResourceGroupName | toString }}"
          cloudName: AzurePublicCloud
          osServicePrincipal.json: |- 
            "{{ .azureOsServicePrincipal | toString }}"
          pullSecret: |- 
            "{{ .openshiftPullSecret | toString }}"
          ssh-publickey: |- 
            "{{ .openshiftSSHPrivateKey | toString }}"
          ssh-privatekey: |- 
            "{{ .openshiftSSHPublicKey | toString }}"
          {{- end }}
          {{- if eq .Values.cloudProvider.name "gcp" }}
          baseDomain: |-
            "{{ .gcpBaseDomain | toString }}"
          projectID: |- 
            "{{ .gcpProjectID | toString }}"
          osServiceAccount.json: |- 
            "{{ .gcpOsServiceAccount | toString }}"
          pullSecret: |- 
            "{{ .openshiftPullSecret | toString }}"
          ssh-publickey: |- 
            "{{ .openshiftSSHPrivateKey | toString }}"
          ssh-privatekey: |- 
            "{{ .openshiftSSHPublicKey | toString }}"
          {{- end }}
          {{- if eq .Values.cloudProvider.name "rhocm" }}
          ocmAPIToken: |-
            "{{ .ocmAPIToken | toString }}"
          {{- end }}