apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-vsphere-certs
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster }}
spec:
  encryptedData:
    .cacert: {{ .Values.provider.cacertificate }}
  template:
    data: null
    metadata:
      name: {{ .Values.cluster }}-vsphere-certs
      namespace: '{{ .Values.cluster }}'
    type: Opaque
