apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-{{ .Values.cluster.imageName }}-{{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "360"
    helm.sh/hook-weight: "360"
spec:
   releaseImage: quay.io/openshift-release-dev/ocp-release:{{ .Values.cluster.imageName }}-x86_64