apiVersion: internal.open-cluster-management.io/v1beta1
kind: ManagedClusterInfo
metadata:
  name: '{{ .Values.cluster.name }}'
  annotations:
    argocd.argoproj.io/sync-wave: "495"
    helm.sh/hook-weight: "495"
  namespace: '{{ .Values.cluster.name }}'