apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster.name }}-ssh-private-key
  annotations:
    argocd.argoproj.io/sync-wave: "455"
    helm.sh/hook-weight: "455"
  namespace: {{ .Values.cluster.name }}
spec:
  data:
  - secretKey: openshiftSSHPrivateKey
    remoteRef: 
      key: {{ .Values.externalSecrets.sshPrivateKeyRemoteRef }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster.name }}-ssh-private-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ssh-privatekey: |-
          {{ "{{ .openshiftSSHPrivateKey | toString }}" }}
  