apiVersion: internal.open-cluster-management.io/v1beta1
kind: ManagedClusterInfo
metadata:
  name: '{{ .Values.cluster }}'
  annotations:
    argocd.argoproj.io/sync-wave: "375"
    helm.sh/hook-weight: "375"
  namespace: '{{ .Values.cluster }}'