apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster }}-azure-creds
  annotations:
    argocd.argoproj.io/sync-wave: "455"
    helm.sh/hook-weight: "455"
  namespace: {{ .Values.cluster }}
spec:
  data:
    - secretKey: azureOsServicePrincipal
      remoteRef:
        key: {{ .Values.secrets.azureSecrets.azureOsServicePrincipalRef }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster }}-azure-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        osServicePrincipal.json: |-
          {{ "{{ .azureOsServicePrincipal | toString }}" }}