{{- if .Values.storage.enabled -}}
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.cluster }}-storage
  annotations:
    argocd.argoproj.io/sync-wave: "460"
    helm.sh/hook-weight: "460"
  namespace: '{{ .Values.cluster }}'
spec:
  clusterDeploymentRef:
    name: '{{ .Values.cluster }}'
  name: storage
  platform:
    azure:
      osDisk:
        diskSizeGB: {{ .Values.storage.diskSize }} 
      type: {{ .Values.storage.machineType }}
      zones:
      - "1"
      - "2"
      - "3"
  labels:
    cluster.ocs.openshift.io/openshift-storage: ''
  replicas: {{ .Values.storage.count }}
{{- end -}}