apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.connection_name }}
  namespace: rhacm-credentials
spec:
  encryptedData:
    metadata: {{ .Values.providerSecret }}
  template:
    metadata:
      name: {{ .Values.connection_name }}
      namespace: rhacm-credentials
      labels:
        cluster.open-cluster-management.io/cloudconnection: ''
        cluster.open-cluster-management.io/provider: aws 
    type: Opaque