apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterpoolName }}-aws-creds
  annotations:
    argocd.argoproj.io/sync-wave: "310"
    helm.sh/hook-weight: "310"
  namespace: rhacm-clusterpools 
spec:
  data:
    - secretKey: awsAccessKey
      remoteRef:
        key: 0d1d17a7-9d6b-a2b4-6b20-04d87f770fce 
    - secretKey: awsSecretKey
      remoteRef:
        key: 57afa209-35b7-da90-5b92-9621cc27030c
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.clusterpoolName }}-aws-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        aws_access_key_id: |-
          {{ "{{ .awsAccessKey | toString }}" }}
        aws_secret_access_key: |-
          {{ "{{ .awsSecretKey | toString }}" }}