apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterpoolName }}-aws-creds
  annotations:
    argocd.argoproj.io/sync-wave: "410"
    helm.sh/hook-weight: "410"
  namespace: rhacm-clusterpools 
spec:
  data:
    - secretKey: awsAccessKey
      remoteRef:
        key: 88671bfc-14d4-29ad-ab9b-950eaac3808f
    - secretKey: awsSecretKey
      remoteRef:
        key: ac307a9e-41fc-23df-2f28-3ce521b971ea
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.clusterpoolName }}-aws-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        aws_access_key_id: |-
          {{ "{{ .awsAccessKey | toString }}" }}
        aws_secret_access_key: |-
          {{ "{{ .awsSecretKey | toString }}" }}