apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: BareMetal
    name: '{{ .Values.cluster }}'
    vendor: OpenShift
    {{- if .Values.clusterSet.enabled }}
    cluster.open-cluster-management.io/clusterset: {{.Values.clusterSet.name}} 
    {{- end}}
  name: '{{ .Values.cluster }}'
  annotations:
    import.open-cluster-management.io/hosting-cluster-name: local-cluster 
    import.open-cluster-management.io/klusterlet-deploy-mode: Hosted
    open-cluster-management/created-via: hypershift
    argocd.argoproj.io/sync-wave: "470"
    helm.sh/hook-weight: "470"
spec:
  hubAcceptsClient: true