apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: {{ .Values.cluster }}
    cluster.open-cluster-management.io/managedCluster: {{ .Values.cluster }}
    kubernetes.io/metadata.name: {{ .Values.cluster }}
    argocd.argoproj.io/sync-wave: "450"
    helm.sh/hook-weight: "450"
  name: {{ .Values.cluster }}