apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster }}-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "455"
    helm.sh/hook-weight: "455"
  namespace: {{ .Values.cluster }}
spec: 
  data:
  - secretKey: openshiftPullSecret
    remoteRef: 
      key: {{ .Values.secrets.openshiftPullSecretRef }} 
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster }}-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}   