apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster }}-aws-creds
  annotations:
    argocd.argoproj.io/sync-wave: "455"
    helm.sh/hook-weight: "455"
  namespace: {{ .Values.cluster }}
spec:
  data:
    - secretKey: awsAccessKey
      remoteRef:
        key: {{ .Values.secrets.awsSecrets.awsAccessKeyRef }}
    - secretKey: awsSecretKey
      remoteRef:
        key: {{ .Values.secrets.awsSecrets.awsSecretKeyRef }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster }}-aws-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        aws_access_key_id: |-
          {{ "{{ .awsAccessKey | toString }}" }}
        aws_secret_access_key: |-
          {{ "{{ .awsSecretKey | toString }}" }}