apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sshkey-cluster-{{ .Values.cluster }}
  annotations:
    argocd.argoproj.io/sync-wave: "455"
    helm.sh/hook-weight: "455"
  namespace: {{ .Values.clusterNamespace }}
spec:
  data:
  - secretKey: openshiftSSHPublicKey
    remoteRef: 
      key: {{ .Values.secrets.openshiftSSHPublicKeyRef }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: sshkey-cluster-{{ .Values.cluster }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        id_rsa.pub: |- 
          '{{ "{{ .openshiftSSHPublicKey | toString }}" }}'
