apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-ssh-private-key
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster }}
spec:
  encryptedData:
    ssh-privatekey: {{ .Values.provider.sshPrivatekey }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ .Values.cluster }}-ssh-private-key
      namespace: '{{ .Values.cluster }}'
    type: Opaque
