apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-aws-creds
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster }}
spec:
  encryptedData:
    aws_access_key_id: {{ .Values.provider.aws_access_key_id }}
    aws_secret_access_key: {{ .Values.provider.aws_secret_access_key }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ .Values.cluster }}-aws-creds
      namespace: {{ .Values.cluster }} 
    type: Opaque
