clusterpoolName:  

imageName: 4.10.18

# Add Cluster to Existing ClusterSet, else it will automatically join the "global"  and "default" ClusterSets
clusterSet:
  name: "multicloud-cluster-set"
  enabled: false 

provider:
  region: 
  baseDomain: 
  sshPublickey: 

masters:
  architecture: amd64
  count: 3
  diskIops: 4000
  diskSize: 100
  diskType: io1
  machineType: m5.xlarge

workers:
  architecture: amd64
  count: 3
  diskIops: 4000
  diskSize: 100
  diskType: io1
  machineType: m5.xlarge

network:
  clusterCidr: 10.128.0.0/14
  machineCidr: 10.0.0.0/16
  serviceCidr: 172.30.0.0/16
